CREATE TABLE DATA_DICTIONARY ( DATA_ID INTEGER, DATA_PROVIDER VARCHAR(1000),DATA_SOURCE VARCHAR(1676), DATA_TYPE VARCHAR(1677),LFIELD VARCHAR(1888), PFIELD VARCHAR(1777) );


CREATE TABLE `hibernate_sequence` (
  `NEXT_VAL` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`NEXT_VAL`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |

insert into hibernate_sequence values( 1 );


